name = "muntsos_blinky"
description = "MuntsOS Embedded Linux Blinky Test"
version = "@@VERSION@@"
licenses = "BSD-1-Clause"
website = "https://github.com/pmunts/muntsos"

authors = ["Philip Munts"]
maintainers = ["Philip Munts <phil@munts.net>"]
maintainers-logins = ["pmunts"]

project-files = ["muntsos_blinky.gpr"]

executables = ["blinky"]

tags = ["embedded", "linux", "muntsos", "blinky", "libsimpleio", "led",
"beaglebone", "pocketbeagle", "raspberrypi"]

[available."case(os)"]
'linux' = true
"..." = false
